"""shareable run links

Revision ID: 1b114f287149
Revises: 921245684924
Create Date: 2026-08-24 15:36:52.814997
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1b114f287149'
down_revision: str | Sequence[str] | None = '921245684924'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('share_token', sa.String(length=64), nullable=True))
    op.add_column('runs', sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_runs_share_token'), 'runs', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_share_token'), table_name='runs')
    op.drop_column('runs', 'shared_at')
    op.drop_column('runs', 'share_token')
    # ### end Alembic commands ###
