"""watched repositories

Revision ID: 476c21b3f202
Revises: ff187be76ccc
Create Date: 2026-08-26 21:03:23.761358
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '476c21b3f202'
down_revision: str | Sequence[str] | None = 'ff187be76ccc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched_repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('schedule', sa.String(length=16), nullable=False),
    sa.Column('health_drop_threshold', sa.Float(), nullable=False),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('last_run_id', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_alert_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_alert_key', sa.String(length=64), nullable=True),
    sa.Column('last_status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'repository_id', name='uq_watch_user_repo')
    )
    op.create_index('ix_watch_due', 'watched_repositories', ['active', 'last_checked_at'], unique=False)
    op.create_index(op.f('ix_watched_repositories_repository_id'), 'watched_repositories', ['repository_id'], unique=False)
    op.create_index(op.f('ix_watched_repositories_user_id'), 'watched_repositories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watched_repositories_user_id'), table_name='watched_repositories')
    op.drop_index(op.f('ix_watched_repositories_repository_id'), table_name='watched_repositories')
    op.drop_index('ix_watch_due', table_name='watched_repositories')
    op.drop_table('watched_repositories')
    # ### end Alembic commands ###
