"""watch alert dedup

Revision ID: 921245684924
Revises: 431abc24634b
Create Date: 2026-08-24 14:40:49.854812
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '921245684924'
down_revision: str | Sequence[str] | None = '431abc24634b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watched_repositories', sa.Column('last_alerted_sha', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watched_repositories', 'last_alerted_sha')
    # ### end Alembic commands ###
